// Authentication is enforced by database.rules.json on the server as well as this UI.
let authService=null,authStarted=false,authUid=null,authEpoch=0,authBusy=false;
const authSubscriptions=[];
const authElement=id=>document.getElementById(id);
function authMessage(message){authElement('auth-status').textContent=message;}
function authLock(){const app=authElement('auth-app');app.hidden=true;app.inert=true;app.style.display='none';authElement('auth-gate').hidden=false;}
function authControls(enabled){authElement('auth-password').disabled=!enabled;authElement('auth-submit').disabled=!enabled;}
function authStop(){for(const [ref,fn] of authSubscriptions.splice(0))ref.off('value',fn);}
function authWatch(path,fn){const ref=db.ref(path);const guarded=snap=>{if(authUid)fn(snap);};authSubscriptions.push([ref,guarded]);ref.on('value',guarded,()=>authDeny('데이터 접근 권한이 없습니다. 팀 관리자에게 문의하세요.'));}
function authDeny(message){authEpoch++;authUid=null;authStop();authLock();db.goOffline();authMessage(message);authControls(!authBusy&&!!JUST_AUTH_CONFIG.teamEmail);}
function authError(error){if(error?.code==='auth/too-many-requests')return '시도가 너무 많습니다. 잠시 후 다시 로그인하세요.';if(error?.code==='auth/network-request-failed')return '인터넷 연결을 확인한 뒤 다시 시도하세요.';return '로그인하지 못했습니다. 비밀번호를 확인하거나 팀 관리자에게 문의하세요.';}
async function authLogin(event){event.preventDefault();if(authBusy||!authService)return;const input=authElement('auth-password'),password=input.value;if(!password)return;authBusy=true;authControls(false);authMessage('로그인하고 있습니다…');try{await authService.signInWithEmailAndPassword(JUST_AUTH_CONFIG.teamEmail,password);}catch(error){authMessage(authError(error));}finally{input.value='';authElement('auth-show-password').checked=false;input.type='password';authBusy=false;authControls(true);}}
async function authLogout(){authLock();authUid=null;authStop();db.goOffline();authControls(false);authMessage('로그아웃하고 있습니다…');try{await authService.signOut();location.reload();}catch{authMessage('로그아웃을 완료하지 못했습니다. 인터넷 연결을 확인하고 다시 시도하세요.');authElement('auth-submit').disabled=false;authElement('auth-submit').textContent='로그아웃 다시 시도';authElement('auth-form').onsubmit=e=>{e.preventDefault();authLogout();};}}
async function authChanged(user,start){const epoch=++authEpoch;authLock();authStop();authUid=null;if(!user){db.goOffline();if(authStarted){location.reload();return;}authControls(!!JUST_AUTH_CONFIG.teamEmail);authMessage(JUST_AUTH_CONFIG.teamEmail?'팀 공용 비밀번호를 입력하세요.':'관리자가 팀 로그인 설정을 완료해야 합니다.');return;}
 authControls(false);authMessage('팀 접근 권한을 확인하고 있습니다…');db.goOnline();try{const member=await db.ref('members/'+user.uid).once('value');if(epoch!==authEpoch)return;if(member.val()!==true){authDeny('팀 접근 권한이 없는 계정입니다. 팀 관리자에게 문의하세요.');return;}if(authStarted){location.reload();return;}authUid=user.uid;authStarted=true;start();authElement('auth-app').hidden=false;authElement('auth-app').inert=false;authElement('auth-app').style.display='';authElement('auth-gate').hidden=true;authElement('auth-password').value='';}catch{if(epoch===authEpoch)authDeny('팀 접근 권한을 확인하지 못했습니다. 인터넷 연결 또는 관리자 설정을 확인하세요.');}}
async function initAuth(start){authLock();authControls(false);db.goOffline();authElement('auth-form').onsubmit=authLogin;authElement('auth-logout').addEventListener('click',authLogout);authElement('auth-show-password').addEventListener('change',e=>authElement('auth-password').type=e.target.checked?'text':'password');try{authService=firebase.auth();await authService.setPersistence(firebase.auth.Auth.Persistence.SESSION);authService.onAuthStateChanged(user=>authChanged(user,start),()=>authDeny('로그인 상태를 확인하지 못했습니다. 새로고침 후 다시 시도하세요.'));}catch{authMessage('로그인 서비스를 불러오지 못했습니다. 인터넷 연결을 확인하고 새로고침하세요.');}}
