// Existing Firebase collections and explicit links are retained; no date-based merging.
const DR = (()=>{
 const list=x=>Object.values(x||{}).filter(x=>x&&typeof x==='object');
 const eq=(a,b)=>String(a??'')===String(b??'');
 function time(s){const m=String(s??'').trim().match(/^(\d{1,5}):([0-5]\d)(?:\.(\d{1,3}))?$/);if(!m)return null;const n=Number(m[1])*60+Number(m[2])+Number('0.'+(m[3]||'0'));return n>0?n:null;}
 function seconds(l){if(l.time!=null)return time(l.time);return Number.isFinite(l.sec)&&l.sec>0?l.sec:null;}
 const valid=l=>l.valid!=='invalid'&&seconds(l)!==null;
 function scope(records,key,id,logs,driver='') {return list(records).filter(r=>(!driver||r.driver===driver)&&(id==='all'||(id==='unlinked'?!list(logs).some(l=>eq(l.id,r[key])):eq(r[key],id))));}
 function stats(laps){const nums=laps.filter(valid).map(seconds);const count=nums.length,avg=count?nums.reduce((s,n)=>s+n,0)/count:null;return{count,all:laps.length,best:count?nums.reduce((a,b)=>Math.min(a,b),Infinity):null,avg,std:count?Math.sqrt(nums.reduce((s,n)=>s+(n-avg)**2,0)/count):null};}
 function mutate(root,kind,record,remove=false,editing=false){
  if(!['testLogs','lapTimes','feedbacks','setupHistory'].includes(kind))throw Error('지원하지 않는 기록입니다.');
  const next={...(root||{})},rows=list(next[kind]),idx=rows.findIndex(r=>eq(r.id,record.id));
  if(remove){next[kind]=rows.filter(r=>!eq(r.id,record.id));return next;}
  if(editing&&idx<0)throw Error('다른 사용자가 이 기록을 삭제했습니다. 새 기록으로 입력하세요.');
  const merged={...(idx>=0?rows[idx]:{}),...record};
  if(kind==='lapTimes'&&(!merged.driver||time(merged.time)===null||!['valid','invalid'].includes(merged.valid)))throw Error('랩 입력값이 올바르지 않습니다.');
  const link=kind==='lapTimes'?'sessionId':kind==='feedbacks'?'testLogLink':kind==='setupHistory'?'sessionId':null;
  if(link&&merged[link]&&!list(next.testLogs).some(l=>eq(l.id,merged[link])) && !eq(rows[idx]?.[link],merged[link]))throw Error('선택한 테스트가 삭제되었습니다. 연결을 다시 선택하세요.');
  if(kind==='feedbacks'&&merged.lapId){const lap=list(next.lapTimes).find(l=>eq(l.id,merged.lapId));if(!lap||!eq(lap.sessionId,merged.testLogLink)||lap.driver!==merged.driver)throw Error('연결할 랩의 테스트와 드라이버가 일치해야 합니다.');}
  if(kind==='lapTimes'&&idx>=0&&list(next.feedbacks).some(f=>eq(f.lapId,record.id))&&(!eq(merged.sessionId,rows[idx].sessionId)||merged.driver!==rows[idx].driver))throw Error('연결된 피드백이 있습니다. 피드백의 랩 연결을 먼저 해제한 뒤 테스트/드라이버를 변경하세요.');
  if(idx>=0)rows[idx]=merged;else rows.push(merged);next[kind]=rows;return next;
 }
 const chronological=rows=>[...rows].sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||(Number(a.createdAt)||Number(a.id)||0)-(Number(b.createdAt)||Number(b.id)||0));
 return{list,eq,time,seconds,valid,scope,stats,mutate,chronological};
})();
let driveScope='all',driveView='log',driveBusy=false,driveReady=false;
let editLogId=null,selectedLogId=null,driveLapEdit=null,driveFeedbackEdit=null,driveSetupEdit=null;
const driveCharts={};
const driveRatings=['cornerEntry','midBalance','exitTraction','steeringResponse','brakeFeel','understeer','oversteer'];
const driveRatingLabels=['코너 진입','중립 밸런스','탈출 트랙션','조향 응답성','브레이크 감각','언더스티어 심함','오버스티어 심함'];
const driveLogFields={date:'log-date',title:'log-title',location:'log-location',purpose:'log-purpose',temp:'log-temp',weather:'log-weather',track:'log-track',result:'log-result',issues:'log-issues',next:'log-next'};
const driveSetupFields={fride:'log-fride',rride:'log-rride',ftire:'log-ftire',rtire:'log-rtire',fcamber:'log-fcamber',rcamber:'log-rcamber',tiretype:'log-tiretype'};
const driveCoolingFields={coolantTemp:'log-coolant-temp',oilTemp:'log-oil-temp',maxRpm:'log-max-rpm',runTime:'log-run-time',runDist:'log-run-dist',fuelUsed:'log-fuel-used',stopReason:'log-stop-reason'};
const driveEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const driveEl=id=>document.getElementById(id);
const driveSet=(id,value)=>{const el=driveEl(id);if(el)el.value=value??'';};
const driveToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const driveId=()=>crypto.randomUUID();
function parseTime(s){return DR.time(s);}
function formatTime(sec){if(!Number.isFinite(sec)||sec<0)return '—';const ms=Math.round(sec*1000);return Math.floor(ms/60000)+':'+((ms%60000)/1000).toFixed(3).padStart(6,'0');}
function driveTitle(l){return [l.date,l.title||l.result?.slice(0,35)||'이름 없는 테스트',l.location].filter(Boolean).join(' · ');}
function driveLabel(id){const l=S.testLogs.find(l=>DR.eq(l.id,id));return l?driveTitle(l):id?'연결된 테스트 없음 (기존 기록)':'미연결';}
function driveRows(kind){const key=kind==='feedbacks'?'testLogLink':'sessionId';return DR.scope(S[kind],key,driveScope,S.testLogs,kind==='setupHistory'?'':v('drive-driver'));}
function driveOptions(id,rows,empty='연결 안함',preferred){const el=driveEl(id);if(!el)return;const old=preferred===undefined?el.value:String(preferred??'');el.innerHTML='<option value="">'+driveEsc(empty)+'</option>'+rows.map(([value,text])=>`<option value="${driveEsc(value)}">${driveEsc(text)}</option>`).join('');if(old&&!rows.some(([k])=>DR.eq(k,old)))el.insertAdjacentHTML('beforeend',`<option value="${driveEsc(old)}">연결된 기록 없음 (기존 값)</option>`);el.value=old;}
function populateTestSessions(){driveOptions('lt-session',S.testLogs.map(l=>[l.id,driveTitle(l)]));}
function populateTestLogLinks(){driveOptions('fb-testlog-link',S.testLogs.map(l=>[l.id,driveTitle(l)]));driveOptions('sh-session',S.testLogs.map(l=>[l.id,driveTitle(l)]));driveLapOptions();}
function populateSetupLinks(){driveOptions('fb-setup-link',S.setupHistory.map(s=>[s.id,s.date+' · '+s.what]));}
function driveLapOptions(){const session=v('fb-testlog-link');driveOptions('fb-lap-link',S.lapTimes.filter(l=>DR.eq(l.sessionId,session)).map(l=>[l.id,l.date+' · '+l.driver+' · '+(l.sessionNum||'')+' '+l.time]));}
function receiveDriving(root){for(const key of ['testLogs','lapTimes','feedbacks','setupHistory'])S[key]=DR.list(root[key]);const first=!driveReady;driveReady=true;if(first&&S.testLogs.length)driveSelect(String(DR.chronological(S.testLogs).at(-1).id));else renderDriving();}
async function driveCommit(kind,record,remove=false,editing=false){
 if(driveBusy)return false;if(!driveReady){setText('drive-status','서버 연결이 완료된 뒤 저장하세요.');return false;}driveBusy=true;setText('drive-status','저장 중…');const controls=[...document.querySelectorAll('#tab-driving button, #tab-driving input, #tab-driving select, #tab-driving textarea')].map(el=>[el,el.disabled]);controls.forEach(([el])=>el.disabled=true);
 try {const saved={...record,updatedAt:Date.now(),...(!editing&&!remove?{createdAt:Date.now()}:{})};const result=await db.ref('just').transaction(root=>{const next=DR.mutate(root,kind,saved,remove,editing);const stamp=new Date(saved.updatedAt).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false,hour:'2-digit',minute:'2-digit'});return {...next,lastSave:stamp,lastModifier:'나 · '+stamp};});if(!result.committed)throw Error('저장되지 않았습니다. 다시 시도하세요.');receiveDriving(result.snapshot.val()||{});renderHome();setText('drive-status',remove?'기록을 삭제했습니다. 연결된 다른 기록은 보존했습니다.':'저장했습니다.');return true;}
 catch(e){setText('drive-status','저장 실패: '+e.message);return false;}finally{driveBusy=false;controls.forEach(([el,disabled])=>el.disabled=disabled);}
}
function driveShow(view){driveOpen(['log','laps','feedback','setup','compare'].includes(view)?view:'log');}
function driveSelect(id){driveScope=id||'all';driveSet('drive-session',driveScope);const log=S.testLogs.find(l=>DR.eq(l.id,driveScope));driveLapEdit=null;driveFeedbackEdit=null;driveSetupEdit=null;driveSet('lt-time','');driveSet('lt-note','');driveSet('lt-valid','valid');driveSet('fb-comment','');
 populateTestSessions();populateTestLogLinks();for(const id of ['lt-session','fb-testlog-link','sh-session'])driveSet(id,log?.id||'');
 if(log){driveFillLog(log);for(const id of ['lt-date','fb-date','sh-date'])driveSet(id,log.date);driveSet('lt-weather',log.weather||'맑음');driveSet('lt-track',log.track||'건조');driveSet('lt-tireset',log.setup?.tiretype||'');}else{clearLogForm();}
 driveSet('fb-lap-link','');driveLapOptions();renderDriving();
}
function initDriving(){initDriveWorkspace();renderDriving();driveEl('fb-testlog-link').addEventListener('change',()=>{driveSet('fb-lap-link','');driveLapOptions();});document.querySelector('#tab-driving').addEventListener('click',e=>{const b=e.target.closest('[data-drive-action]');if(!b)return;const id=b.dataset.id;({log:editLog,lap:driveEditLap,feedback:driveEditFeedback,deleteLog,deleteLap,deleteFeedback:driveDeleteFeedback,setup:driveEditSetup,deleteSetup,laps:showSessionLaps,compare:compareLogs})[b.dataset.driveAction]?.(id);});}
function driveButton(action,id,text){return `<button type="button" class="btn btn-ghost btn-sm" data-drive-action="${action}" data-id="${driveEsc(id)}">${text}</button>`;}
function renderDriving(){if(!driveEl('drive-session'))return;
 const session=driveEl('drive-session');session.innerHTML='<option value="all">전체 테스트</option><option value="unlinked">미연결 기록</option>'+S.testLogs.map(l=>`<option value="${driveEsc(l.id)}">${driveEsc(driveTitle(l))}</option>`).join('');if(driveScope!=='all'&&driveScope!=='unlinked'&&!S.testLogs.some(l=>DR.eq(l.id,driveScope)))driveScope='unlinked';session.value=driveScope;
 const drivers=[...new Set([...S.lapTimes,...S.feedbacks].map(r=>r.driver).filter(Boolean))].sort();driveOptions('drive-driver',drivers.map(d=>[d,d]),'전체 드라이버');
 const laps=driveRows('lapTimes'),fbs=driveRows('feedbacks'),stats=DR.stats(laps);
 driveEl('drive-summary').innerHTML=[['랩 기록',laps.length+'개 · 유효 '+stats.count+'개'],['최고 랩타임',formatTime(stats.best)],['평균 랩타임',formatTime(stats.avg)],['드라이버 메모',fbs.length+'개']].map(([k,val])=>`<div><span>${k}</span><strong>${driveEsc(val)}</strong></div>`).join('');
 setText('drive-context',driveScope==='all'?'전체 기록을 표시합니다. 테스트를 선택하면 입력 날짜·조건·연결을 함께 설정합니다.':driveScope==='unlinked'?'테스트에 연결되지 않았거나 연결된 테스트가 삭제된 기록입니다. 편집에서 원하는 테스트에 연결할 수 있습니다.':driveLabel(driveScope));
 populateTestSessions();populateTestLogLinks();populateSetupLinks();renderTestLogs();renderDriveComparison();
 setText('drive-lap-save',driveLapEdit?'랩 기록 수정 저장':'랩 기록 저장');setText('drive-fb-save',driveFeedbackEdit?'메모 수정 저장':'메모 저장');setText('drive-setup-save',driveSetupEdit?'세팅 수정 저장':'셋업 변경 기록');
 renderDriveWorkspace();
}
function driveFillLog(log){editLogId=log.id;selectedLogId=log.id;for(const [k,id] of Object.entries(driveLogFields))driveSet(id,log[k]);for(const [k,id] of Object.entries(driveSetupFields))driveSet(id,log.setup?.[k]);for(const [k,id] of Object.entries(driveCoolingFields))driveSet(id,log.cooling?.[k]);for(const [k,id] of [['oilLeak','log-oil-leak'],['coolantLeak','log-coolant-leak'],['boltLoose','log-bolt-loose']])driveEl(id).checked=!!log.cooling?.[k];setText('log-form-title','테스트 편집');}
function clearLogForm(){editLogId=null;selectedLogId=null;for(const id of [...Object.values(driveLogFields),...Object.values(driveSetupFields),...Object.values(driveCoolingFields)])driveSet(id,'');for(const id of ['log-oil-leak','log-coolant-leak','log-bolt-loose'])driveEl(id).checked=false;driveSet('log-date',driveToday());driveSet('log-weather','맑음');driveSet('log-track','건조');setText('log-form-title','새 테스트 작성');}
function showNewLog(){clearLogForm();driveShow('log');}
function selectLog(id){editLog(id);}
function editLog(id){driveSelect(String(id));driveShow('log');}
function driveDate(id){const value=v(id);if(!competitionDay(value))throw Error('올바른 날짜를 입력하세요.');return value;}
async function saveLog(){try{const old=S.testLogs.find(l=>DR.eq(l.id,editLogId));const read=map=>Object.fromEntries(Object.entries(map).map(([k,id])=>[k,v(id)]));if(!v('log-title').trim())throw Error('테스트 이름을 입력하세요.');const record={...read(driveLogFields),id:editLogId??driveId(),date:driveDate('log-date'),setup:{...(old?.setup||{}),...read(driveSetupFields)},cooling:{...(old?.cooling||{}),...read(driveCoolingFields)}};for(const [k,id] of [['oilLeak','log-oil-leak'],['coolantLeak','log-coolant-leak'],['boltLoose','log-bolt-loose']])record.cooling[k]=driveEl(id).checked;
 if(await driveCommit('testLogs',record,false,editLogId!=null)){driveSelect(String(record.id));driveSaved('log');}}catch(e){setText('drive-status',e.message);}}
function renderTestLogs(){renderDriveSessionList();}
function filterLogs(){renderTestLogs();}
async function deleteLog(id){if(confirm('테스트를 삭제할까요? 연결된 랩과 피드백은 미연결 기록에서 계속 볼 수 있습니다.')){if(await driveCommit('testLogs',{id},true)){if(DR.eq(editLogId,id))clearLogForm();}}}
function showSessionLaps(id){driveSelect(String(id));driveShow('laps');}
function driveNewLap(){driveLapEdit=null;for(const id of ['lt-time','lt-note'])driveSet(id,'');renderDriving();}
function driveEditLap(id){const l=S.lapTimes.find(l=>DR.eq(l.id,id));if(!l)return;driveLapEdit=l.id;const map={driver:'driver',date:'date',time:'time',weather:'weather',track:'track',note:'note',sessionId:'session',sessionNum:'session-num',valid:'valid',tireSet:'tireset',setupVer:'setup-ver'};for(const [key,suffix] of Object.entries(map))driveSet('lt-'+suffix,l[key]??(key==='valid'?'valid':''));populateTestSessions();driveOptions('lt-session',S.testLogs.map(l=>[l.id,driveTitle(l)]),'연결 안함',l.sessionId||'');driveShow('laps');}
async function addLapTime(){try{const driver=v('lt-driver').trim(),sec=parseTime(v('lt-time'));if(!driver||sec===null)throw Error('드라이버와 올바른 랩타임을 입력하세요. 예: 1:23.456 (초 00~59, 0초 초과)');const record={id:driveLapEdit??driveId(),driver,date:driveDate('lt-date'),time:formatTime(sec),sec,weather:v('lt-weather'),track:v('lt-track'),note:v('lt-note'),sessionId:v('lt-session'),sessionNum:v('lt-session-num'),valid:v('lt-valid'),tireSet:v('lt-tireset'),setupVer:v('lt-setup-ver')};if(await driveCommit('lapTimes',record,false,driveLapEdit!=null)){driveNewLap();driveSet('fb-driver',driver);driveSaved('laps');}}catch(e){setText('drive-status',e.message);}}
async function deleteLap(id){if(confirm('이 랩 기록을 삭제할까요? 피드백은 보존됩니다.')){if(await driveCommit('lapTimes',{id},true)){if(DR.eq(driveLapEdit,id))driveNewLap();}}}
function renderLapTable(){const laps=driveRows('lapTimes'),bests=Object.create(null);for(const l of laps.filter(DR.valid))bests[l.driver]=Math.min(bests[l.driver]??Infinity,DR.seconds(l));driveEl('lap-tbody').innerHTML=laps.map((l,i)=>`<tr><td>${i+1}</td><td>${driveEsc(l.driver)}</td><td>${driveEsc(l.date)}</td><td class="${DR.valid(l)&&DR.seconds(l)===bests[l.driver]?'best-time':''}">${driveEsc(l.time||formatTime(l.sec))}${!DR.valid(l)?' · 무효/형식 확인':''}</td><td>${driveEsc(l.weather)}</td><td>${driveEsc(l.track)}</td><td>${driveEsc(driveLabel(l.sessionId))}<br>${driveEsc(l.sessionNum)}</td><td>${driveEsc(l.tireSet)}</td><td>${driveEsc(l.setupVer)}</td><td>${driveEsc(l.note)}</td><td>${driveButton('lap',l.id,'편집')}${driveButton('deleteLap',l.id,'삭제')}</td></tr>`).join('')||'<tr><td colspan="11">이 범위의 랩 기록이 없습니다.</td></tr>';}
function renderDriverStats(){const laps=driveRows('lapTimes');driveEl('driver-stats-list').innerHTML=[...new Set(laps.map(l=>l.driver))].map(d=>{const s=DR.stats(laps.filter(l=>l.driver===d));return `<article class="drive-stat"><strong>${driveEsc(d)}</strong><p>전체 ${s.all}랩 · 유효 ${s.count}랩</p><p>최고 ${formatTime(s.best)} · 평균 ${formatTime(s.avg)}</p><p>표준편차 ${s.std==null?'—':s.std.toFixed(3)+'초'}</p></article>`;}).join('')||'<p class="drive-help">랩 기록을 추가하면 통계가 표시됩니다.</p>';}
function updateRating(key,val){setText('rv-'+key,val);const el=driveEl('fb-'+key);if(el)el.style.background=`linear-gradient(90deg,#ff0000 ${(Number(val)-1)/9*100}%,#222 0)`;}
function driveNewFeedback(){driveFeedbackEdit=null;driveEl('drive-rate-enabled').checked=false;driveToggleRatings();driveSet('fb-comment','');driveSet('fb-lap-link','');driveRatings.forEach(k=>{driveSet('fb-'+k,5);updateRating(k,5);});renderDriving();}
function driveFeedbackLap(id){const l=S.lapTimes.find(l=>DR.eq(l.id,id));if(l){driveSet('fb-driver',l.driver);driveSet('fb-date',l.date);}}
function driveEditFeedback(id){const f=S.feedbacks.find(f=>DR.eq(f.id,id));if(!f)return;driveFeedbackEdit=f.id;driveEl('drive-rate-enabled').checked=driveRatings.every(k=>Number.isFinite(f[k]));driveToggleRatings();for(const key of ['driver','date','comment'])driveSet('fb-'+key,f[key]);driveOptions('fb-testlog-link',S.testLogs.map(l=>[l.id,driveTitle(l)]),'연결 안함',f.testLogLink||'');driveOptions('fb-setup-link',S.setupHistory.map(s=>[s.id,s.what]),'없음',f.setupLink||'');driveLapOptions();driveOptions('fb-lap-link',S.lapTimes.filter(l=>DR.eq(l.sessionId,f.testLogLink)).map(l=>[l.id,l.driver+' · '+l.time]),'연결 안함',f.lapId||'');driveRatings.forEach(k=>{driveSet('fb-'+k,f[k]??5);updateRating(k,f[k]??5);});driveShow('feedback');}
async function saveFeedback(){try{const driver=v('fb-driver').trim(),comment=v('fb-comment').trim(),rated=driveEl('drive-rate-enabled').checked;if(!driver)throw Error('드라이버를 입력하세요.');if(!comment&&!rated)throw Error('주행 메모를 입력하거나 항목별 점수를 기록하세요.');const vals=rated?Object.fromEntries(driveRatings.map(k=>[k,Number(v('fb-'+k))])):{};if(Object.values(vals).some(n=>!Number.isInteger(n)||n<1||n>10))throw Error('평가는 1~10점으로 입력하세요.');const record={id:driveFeedbackEdit??driveId(),driver,date:driveDate('fb-date'),testLogLink:v('fb-testlog-link'),lapId:v('fb-lap-link'),setupLink:v('fb-setup-link'),...vals,...(rated?{qualityScore:driveRatings.slice(0,5).reduce((s,k)=>s+vals[k],0)/5}:{}),comment};if(await driveCommit('feedbacks',record,false,driveFeedbackEdit!=null)){driveNewFeedback();driveSaved('feedback');}}catch(e){setText('drive-status',e.message);}}
async function driveDeleteFeedback(id){if(confirm('이 피드백을 삭제할까요?')){if(await driveCommit('feedbacks',{id},true)){if(DR.eq(driveFeedbackEdit,id))driveNewFeedback();}}}
function renderFeedbackList(){driveEl('drive-feedback-list').innerHTML=driveRows('feedbacks').map(f=>`<article class="drive-stat"><strong>${driveEsc(f.driver)} · ${driveEsc(f.date)}</strong><p class="drive-help">${driveEsc(driveLabel(f.testLogLink))}${f.lapId?' · 랩 '+driveEsc(S.lapTimes.find(l=>DR.eq(l.id,f.lapId))?.time||'삭제된 기록'):''}</p><p>${driveEsc(f.comment||'코멘트 없음')}</p><p class="drive-help">${driveRatings.filter(k=>f[k]!=null).map((k,i)=>driveRatingLabels[driveRatings.indexOf(k)]+' '+driveEsc(f[k])).join(' · ')||'이전 평가 형식: '+driveEsc(JSON.stringify(Object.fromEntries(['handling','braking','accel','comfort','overall'].filter(k=>f[k]!=null).map(k=>[k,f[k]]))))}</p>${driveButton('feedback',f.id,'편집')}${driveButton('deleteFeedback',f.id,'삭제')}</article>`).join('')||'<p class="drive-help">이 범위의 피드백이 없습니다.</p>';}
function driveNewSetup(){driveSetupEdit=null;for(const id of ['sh-what','sh-change','sh-why','sh-expect'])driveSet(id,'');renderDriving();}
function driveEditSetup(id){const sh=S.setupHistory.find(r=>DR.eq(r.id,id));if(!sh)return;driveSetupEdit=sh.id;for(const k of ['date','what','change','why','expect'])driveSet('sh-'+k,sh[k]);driveOptions('sh-session',S.testLogs.map(l=>[l.id,driveTitle(l)]),'연결 안함',sh.sessionId||'');driveShow('setup');}
async function saveSetupChange(){try{const what=v('sh-what').trim();if(!what)throw Error('변경 항목을 입력하세요.');const record={id:driveSetupEdit??driveId(),date:driveDate('sh-date'),sessionId:v('sh-session'),what,change:v('sh-change'),why:v('sh-why'),expect:v('sh-expect')};if(await driveCommit('setupHistory',record,false,driveSetupEdit!=null)){driveNewSetup();driveSaved('setup');}}catch(e){setText('drive-status',e.message);}}
async function deleteSetup(id){if(confirm('이 셋업 변경 기록을 삭제할까요?')){if(await driveCommit('setupHistory',{id},true)&&DR.eq(driveSetupEdit,id))driveNewSetup();}}
function renderSetupHistory(){driveEl('setup-history-list').innerHTML=driveRows('setupHistory').map(s=>`<article class="drive-stat"><strong>${driveEsc(s.date)} · ${driveEsc(s.what)}</strong><p>${driveEsc(s.change)}</p><p>${driveEsc(s.why)}</p><p>${driveEsc(s.expect)}</p><p class="drive-help">${driveEsc(driveLabel(s.sessionId))}</p>${driveButton('setup',s.id,'편집')}${driveButton('deleteSetup',s.id,'삭제')}</article>`).join('')||'<p class="drive-help">이 범위의 셋업 변경 기록이 없습니다.</p>';}
function driveChart(id,type,data,extra={}){if(driveCharts[id]){driveCharts[id].destroy();delete driveCharts[id];}if(typeof Chart==='undefined')return;driveCharts[id]=new Chart(driveEl(id).getContext('2d'),{type,data,options:{responsive:true,animation:false,plugins:{legend:{labels:{color:'#aaa'}}},...extra}});}
function renderLapCharts(){const laps=DR.chronological(driveRows('lapTimes').filter(DR.valid)),drivers=[...new Set(laps.map(l=>l.driver))],colors=['#ff5555','#55cc88','#55aaff','#ffaa55'];driveChart('lapTrendChart','line',{labels:laps.map((l,i)=>(i+1)+' · '+l.date+' '+l.time),datasets:drivers.map((d,i)=>({label:d,data:laps.map(l=>l.driver===d?DR.seconds(l):null),borderColor:colors[i%4],spanGaps:true,tension:0}))});driveChart('lapCompareChart','bar',{labels:drivers,datasets:[{label:'최고 유효 랩 (초)',data:drivers.map(d=>DR.stats(laps.filter(l=>l.driver===d)).best),backgroundColor:'#ff5555'}]});}
function renderFeedbackCharts(){const fbs=DR.chronological(driveRows('feedbacks').filter(f=>driveRatings.every(k=>Number.isFinite(f[k]))));driveChart('radarChart','radar',{labels:driveRatingLabels,datasets:fbs.slice(-3).map((f,i)=>({label:f.driver+' · '+f.date,data:driveRatings.map(k=>f[k]),borderColor:['#ff5555','#55cc88','#55aaff'][i]}))},{scales:{r:{min:0,max:10,ticks:{backdropColor:'transparent',color:'#aaa'},pointLabels:{color:'#aaa'}}}});driveChart('fbTrendChart','line',{labels:fbs.map(f=>f.date+' · '+f.driver),datasets:driveRatings.slice(0,5).map((k,i)=>({label:driveRatingLabels[i],data:fbs.map(f=>f[k]),borderColor:['#ff5555','#55cc88','#55aaff','#ffaa55','#cc88ff'][i],tension:0}))},{scales:{y:{min:1,max:10}}});}
function compareLogs(id){driveOptions('drive-after',S.testLogs.map(l=>[l.id,driveTitle(l)]),'선택',id);driveShow('compare');}
function renderDriveComparison(){const rows=S.testLogs.map(l=>[l.id,driveTitle(l)]);driveOptions('drive-before',rows,'선택');driveOptions('drive-after',rows,'선택');const a=S.testLogs.find(l=>DR.eq(l.id,v('drive-before'))),b=S.testLogs.find(l=>DR.eq(l.id,v('drive-after'))),el=driveEl('drive-comparison');if(!a||!b||DR.eq(a.id,b.id)){el.innerHTML='<p class="drive-help">서로 다른 테스트 두 개를 선택하세요.</p>';return;}
 const fields=[['장소','location'],['날씨','weather'],['노면','track'],['기온','temp'],['목적','purpose'],['앞 차고','setup.fride'],['뒤 차고','setup.rride'],['앞 공기압','setup.ftire'],['뒤 공기압','setup.rtire'],['앞 캠버','setup.fcamber'],['뒤 캠버','setup.rcamber'],['타이어','setup.tiretype'],['결과','result'],['이슈','issues'],['다음 조치','next']];const get=(o,path)=>path.split('.').reduce((v,k)=>v?.[k],o);
 const drivers=[...new Set([...S.lapTimes.filter(l=>DR.eq(l.sessionId,a.id)||DR.eq(l.sessionId,b.id)),...S.feedbacks.filter(f=>DR.eq(f.testLogLink,a.id)||DR.eq(f.testLogLink,b.id))].map(l=>l.driver))].filter(d=>!v('drive-driver')||d===v('drive-driver'));
 el.innerHTML='<div class="drive-table"><table class="lap-table"><thead><tr><th>항목</th><th>변경 전</th><th>변경 후</th></tr></thead><tbody>'+fields.map(([label,key])=>`<tr><td>${label}</td><td>${driveEsc(get(a,key)===''?'—':get(a,key)??'—')}</td><td>${driveEsc(get(b,key)===''?'—':get(b,key)??'—')}</td></tr>`).join('')+'</tbody></table></div>'+drivers.map(d=>{const sa=DR.stats(DR.scope(S.lapTimes,'sessionId',String(a.id),S.testLogs,d)),sb=DR.stats(DR.scope(S.lapTimes,'sessionId',String(b.id),S.testLogs,d));const fb=id=>DR.scope(S.feedbacks,'testLogLink',String(id),S.testLogs,d).map(f=>f.comment).filter(Boolean).join(' / ');return `<article class="drive-stat"><h3>${driveEsc(d)}</h3><p>유효 랩 ${sa.count} → ${sb.count} · 최고 ${formatTime(sa.best)} → ${formatTime(sb.best)}</p><p>평균 ${formatTime(sa.avg)} → ${formatTime(sb.avg)}${sa.avg!=null&&sb.avg!=null?' · 평균 차이 '+(sb.avg-sa.avg>=0?'+':'')+(sb.avg-sa.avg).toFixed(3)+'초':''}</p><p>변경 전 피드백: ${driveEsc(fb(a.id)||'없음')}</p><p>변경 후 피드백: ${driveEsc(fb(b.id)||'없음')}</p></article>`;}).join('');}
if(typeof module!=='undefined')module.exports={DR,formatTime};
