const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('js/auth.js','utf8');
function harness(member=true){const elements={},reads=[],callbacks=[],detached=[];let started=0,reloaded=0,offline=0;const el=id=>elements[id]??=( {hidden:false,inert:false,disabled:false,value:'',style:{},addEventListener(){}} );const c=vm.createContext({document:{getElementById:el},JUST_AUTH_CONFIG:{teamEmail:'team@example.invalid'},db:{goOffline:()=>offline++,goOnline(){},ref:path=>({once:async()=>{reads.push(path);return{val:()=>member};},on:(type,fn,cancel)=>callbacks.push({fn,cancel}),off:(type,fn)=>detached.push(fn)})},location:{reload:()=>reloaded++}});vm.runInContext(source,c);c.start=()=>started++;return{c,el,reads,callbacks,detached,get started(){return started},get reloaded(){return reloaded},get offline(){return offline}};}
test('signed-out visitors never start app or read shared data',async()=>{const h=harness();await vm.runInContext('authChanged(null,start)',h.c);assert.equal(h.started,0);assert.deepEqual(h.reads,[]);assert.equal(h.el('auth-app').hidden,true);assert.equal(h.el('auth-app').inert,true);assert.equal(h.offline,1);});
test('only approved membership starts app; unauthorized users remain locked',async()=>{for(const member of [true,false,null,'true']){const h=harness(member);await vm.runInContext("authChanged({uid:'team'},start)",h.c);assert.equal(h.started,member===true?1:0);assert.deepEqual(h.reads,['members/team']);assert.equal(h.el('auth-app').hidden,member!==true);}});
test('revoked database permission detaches listeners, locks view and stops connection',async()=>{const h=harness();await vm.runInContext("authChanged({uid:'team'},start)",h.c);vm.runInContext("authWatch('just',()=>{})",h.c);h.callbacks[0].cancel();assert.equal(h.el('auth-app').hidden,true);assert.equal(h.detached.length,1);assert.equal(h.offline,1);});
test('sign-out after starting reloads to clear application data and forms',async()=>{const h=harness();await vm.runInContext("authChanged({uid:'team'},start)",h.c);await vm.runInContext('authChanged(null,start)',h.c);assert.equal(h.reloaded,1);assert.equal(h.el('auth-app').hidden,true);});
test('stale membership result after sign-out cannot unlock the app',async()=>{const h=harness();let resolve;h.c.db.ref=()=>({once:()=>new Promise(r=>resolve=r)});const pending=vm.runInContext("authChanged({uid:'team'},start)",h.c);await vm.runInContext('authChanged(null,start)',h.c);resolve({val:()=>true});await pending;assert.equal(h.started,0);assert.equal(h.el('auth-app').hidden,true);});
test('failed password is cleared, errors are generic, double submits are ignored',async()=>{const h=harness();let reject,calls=0;h.c.signin=()=>{calls++;return new Promise((r,j)=>reject=j)};vm.runInContext('authService={signInWithEmailAndPassword:signin}',h.c);h.el('auth-password').value='private-example';const p=vm.runInContext('authLogin({preventDefault(){}})',h.c);await vm.runInContext('authLogin({preventDefault(){}})',h.c);assert.equal(calls,1);reject({code:'auth/wrong-password'});await p;assert.equal(h.el('auth-password').value,'');assert.equal(h.el('auth-submit').disabled,false);assert.doesNotMatch(h.el('auth-status').textContent,/private-example/);});
test('rule policy denies guests, anonymous users, and nonmembers; clients cannot grant membership',()=>{const rules=JSON.parse(fs.readFileSync('database.rules.json','utf8')).rules;assert.equal(rules['.read'],false);assert.equal(rules['.write'],false);assert.equal(rules.members.$uid['.write'],false);for(const action of ['.read','.write'])for(const [auth,expected] of [[null,false],[{uid:'other',token:{firebase:{sign_in_provider:'password'}}},false],[{uid:'team',token:{firebase:{sign_in_provider:'anonymous'}}},false],[{uid:'team',token:{firebase:{sign_in_provider:'password'}}},true]]){const root={child:()=>({child:uid=>({val:()=>uid==='team'})})};assert.equal(vm.runInNewContext(rules.just[action],{auth,root}),expected);}});
