const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/driving.js','utf8'),workspace=fs.readFileSync('js/drive-workspace.js','utf8');
function feedback(rated=false,comment='주행 메모'){
 const fields={'fb-driver':'Kim','fb-date':'2026-09-15','fb-comment':comment,'fb-testlog-link':'session','fb-lap-link':'','fb-setup-link':''};
 const messages=[],saved=[];const c=vm.createContext({v:id=>fields[id]??'5',document:{getElementById:()=>({checked:rated})},setText:(id,t)=>messages.push(t),competitionDay:()=>true,crypto:{randomUUID:()=> 'new'},S:{}});
 vm.runInContext(source,c);c.capture=r=>saved.push(r);vm.runInContext('driveCommit=async(k,r)=>{capture(r);return true};driveNewFeedback=()=>{};driveSaved=()=>{}',c);return{c,messages,saved};
}
test('quick memo saves no fabricated rating values',async()=>{const x=feedback();await vm.runInContext('saveFeedback()',x.c);assert.equal(x.saved.length,1);assert.equal(x.saved[0].comment,'주행 메모');assert.equal('qualityScore' in x.saved[0],false);assert.equal('cornerEntry' in x.saved[0],false);});
test('empty memo needs explicit ratings; enabled ratings are saved',async()=>{const x=feedback(false,'');await vm.runInContext('saveFeedback()',x.c);assert.equal(x.saved.length,0);assert.match(x.messages.at(-1),/메모/);const y=feedback(true,'');await vm.runInContext('saveFeedback()',y.c);assert.equal(y.saved[0].qualityScore,5);assert.equal(y.saved[0].understeer,5);});
test('editing text without ratings preserves existing scores and legacy fields',async()=>{const x=feedback();await vm.runInContext('saveFeedback()',x.c);x.c.record=x.saved[0];const r=vm.runInContext("DR.mutate({testLogs:[{id:'session'}],feedbacks:[{id:'new',cornerEntry:8,overall:7,custom:'keep'}]},'feedbacks',record,false,true)",x.c);assert.equal(r.feedbacks[0].cornerEntry,8);assert.equal(r.feedbacks[0].overall,7);assert.equal(r.feedbacks[0].custom,'keep');});
test('dialog prevents draft dismissal and cannot close during save',()=>{let closed=0;const c=vm.createContext({driveBusy:false,driveEl:()=>({close:()=>closed++}),confirm:()=>false});vm.runInContext(workspace,c);vm.runInContext('dwDirty=true;driveClose()',c);assert.equal(closed,0);vm.runInContext('driveClose(true)',c);assert.equal(closed,1);c.driveBusy=true;vm.runInContext('driveClose(true)',c);assert.equal(closed,1);});
test('new records reset the edited record link to the selected test',()=>{const fields={};const c=vm.createContext({S:{testLogs:[{id:'selected',date:'2026-09-15'}]},DR:{eq:(a,b)=>a===b},driveScope:'selected',driveSet:(id,v)=>fields[id]=v,driveToday:()=> 'today',driveLapOptions:()=>{}});vm.runInContext(workspace,c);for(const kind of ['laps','feedback','setup'])vm.runInContext(`drivePrepareNew('${kind}')`,c);assert.equal(fields['lt-session'],'selected');assert.equal(fields['fb-testlog-link'],'selected');assert.equal(fields['sh-session'],'selected');assert.equal(fields['fb-setup-link'],'');c.driveScope='all';vm.runInContext("drivePrepareNew('laps')",c);assert.equal(fields['lt-session'],'');assert.equal(fields['lt-date'],'today');});
